### ISSUE TITLE
Problem plotting timeseries with large mean but small range

### ISSUE THREAD

**Issue by dlrhodson** [ajheaps/cf-plot#7]
Hi Andy,

  Just a minor issue I've had with plotting ocean salinity timeseries. These typically have a mean of ~34 but very small (<0.001) variations about that mean. `lineplot` fails when I attempt to plot this (see attached example).
[example.tar.gz](https://github.com/ajheaps/cf-plot/files/9672791/example.tar.gz)

```
[dlrhodso@sci1 monitoring]$ ./lineplot_example.py 
Traceback (most recent call last):
  File "./lineplot_example.py", line 10, in <module>
    cfp.lineplot(data)
  File "/apps/jasmin/jaspy/miniconda_envs/jaspy3.8/m3-4.9.2/envs/jaspy3.8-m3-4.9.2-r20211105/lib/python3.8/site-packages/cfplot/cfplot.py", line 6690, in lineplot
    yticks, ymult = gvals(dmin=miny, dmax=maxy, mod=mod)
TypeError: cannot unpack non-iterable NoneType object

```

The problem seems to be around line 3227 in `cf_plot`  ie `gvals()`
```
    # Modify if requested or if out of range 0.001 to 2000000
    if data_range < 0.001:
        while dmax1 <= 3:
            dmin1 = dmin1 * 10.0
            dmax1 = dmax1 * 10.0
            data_range = dmax1 - dmin1
            mult = mult - 1

```

for the salinity data  `data_range `is  `0.0004`  but the line `while dmax1 <= 3:` is skipped over, because `dmax1` is ~34.

If I replace `while dmax1 <= 3:` with `while data_range < 0.001:` this bug is fixed!

It's a minor issue that will probably only affect a few ocean folk, but thought I'd mention it!
Dan

**Comment by ajheaps** [comment]
Hi Dan,
This issue looks to be solved by the time cf-plot gets to version 3.1.26.  The version on JASMIN jaspy is 3.1.16.  To load your own version try doing:
pip install --user cf-plot==3.1.26
and then restart python.  
import cf
import cfplot as cfp
cfp.__version__ 
should then point to the version of cf-plot in your home directory

This version will be picked up all the time rather than the one from jaspy so be aware that when jaspy gets upgraded you might end up picking up an older version of cf-plot.

**Comment by dlrhodson** [comment]
Aha - thanks! I did not know about pip install --user !
Yes - that fixes it - thanks. In future, I will check the current version in the repository!

**Comment by ajheaps** [comment]
Looks okay in cf-view as well!

**Comment by ajheaps** [comment]
I'll close this ticket now as it has been resolved.
